//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpOnvifServer.Credential
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", ConfigurationName="SharpOnvifServer.Credential.CredentialPort")]
    public interface CredentialPort
    {
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Capabilities")]
        SharpOnvifServer.Credential.ServiceCapabilities GetServiceCapabilities();
        
        // CODEGEN: Parameter 'FormatTypeInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="FormatTypeInfo")]
        SharpOnvifServer.Credential.GetSupportedFormatTypesResponse GetSupportedFormatTypes(SharpOnvifServer.Credential.GetSupportedFormatTypesRequest request);
        
        // CODEGEN: Parameter 'CredentialInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="CredentialInfo")]
        SharpOnvifServer.Credential.GetCredentialInfoResponse GetCredentialInfo(SharpOnvifServer.Credential.GetCredentialInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.GetCredentialInfoListResponse GetCredentialInfoList(SharpOnvifServer.Credential.GetCredentialInfoListRequest request);
        
        // CODEGEN: Parameter 'Credential' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentials")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Credential")]
        SharpOnvifServer.Credential.GetCredentialsResponse GetCredentials(SharpOnvifServer.Credential.GetCredentialsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.GetCredentialListResponse GetCredentialList(SharpOnvifServer.Credential.GetCredentialListRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/CreateCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Token")]
        string CreateCredential(SharpOnvifServer.Credential.Credential Credential, SharpOnvifServer.Credential.CredentialState State);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetCredential(SharpOnvifServer.Credential.CredentialData CredentialData);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/ModifyCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ModifyCredential(SharpOnvifServer.Credential.Credential Credential);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteCredential(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialState")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="State")]
        SharpOnvifServer.Credential.CredentialState GetCredentialState(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/EnableCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void EnableCredential(string Token, string Reason);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DisableCredential")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DisableCredential(string Token, string Reason);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ResetAntipassbackViolation(string CredentialToken);
        
        // CODEGEN: Parameter 'CredentialIdentifier' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="CredentialIdentifier")]
        SharpOnvifServer.Credential.GetCredentialIdentifiersResponse GetCredentialIdentifiers(SharpOnvifServer.Credential.GetCredentialIdentifiersRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetCredentialIdentifier(string CredentialToken, SharpOnvifServer.Credential.CredentialIdentifier CredentialIdentifier);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteCredentialIdentifier(string CredentialToken, string CredentialIdentifierTypeName);
        
        // CODEGEN: Parameter 'CredentialAccessProfile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="CredentialAccessProfile")]
        SharpOnvifServer.Credential.GetCredentialAccessProfilesResponse GetCredentialAccessProfiles(SharpOnvifServer.Credential.GetCredentialAccessProfilesRequest request);
        
        // CODEGEN: Parameter 'CredentialAccessProfile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.SetCredentialAccessProfilesResponse SetCredentialAccessProfiles(SharpOnvifServer.Credential.SetCredentialAccessProfilesRequest request);
        
        // CODEGEN: Parameter 'AccessProfileToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.DeleteCredentialAccessProfilesResponse DeleteCredentialAccessProfiles(SharpOnvifServer.Credential.DeleteCredentialAccessProfilesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetWhitelist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.GetWhitelistResponse GetWhitelist(SharpOnvifServer.Credential.GetWhitelistRequest request);
        
        // CODEGEN: Parameter 'Identifier' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/AddToWhitelist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.AddToWhitelistResponse AddToWhitelist(SharpOnvifServer.Credential.AddToWhitelistRequest request);
        
        // CODEGEN: Parameter 'Identifier' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/RemoveFromWhitelist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.RemoveFromWhitelistResponse RemoveFromWhitelist(SharpOnvifServer.Credential.RemoveFromWhitelistRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteWhitelist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteWhitelist();
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetBlacklist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.GetBlacklistResponse GetBlacklist(SharpOnvifServer.Credential.GetBlacklistRequest request);
        
        // CODEGEN: Parameter 'Identifier' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/AddToBlacklist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.AddToBlacklistResponse AddToBlacklist(SharpOnvifServer.Credential.AddToBlacklistRequest request);
        
        // CODEGEN: Parameter 'Identifier' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/RemoveFromBlacklist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        SharpOnvifServer.Credential.RemoveFromBlacklistResponse RemoveFromBlacklist(SharpOnvifServer.Credential.RemoveFromBlacklistRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteBlacklist")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteBlacklist();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class ServiceCapabilities
    {
        
        private string[] supportedIdentifierTypeField;
        
        private ServiceCapabilitiesExtension extensionField;
        
        private uint maxLimitField;
        
        private bool credentialValiditySupportedField;
        
        private bool credentialAccessProfileValiditySupportedField;
        
        private bool validitySupportsTimeValueField;
        
        private uint maxCredentialsField;
        
        private uint maxAccessProfilesPerCredentialField;
        
        private bool resetAntipassbackSupportedField;
        
        private bool clientSuppliedTokenSupportedField;
        
        private string defaultCredentialSuspensionDurationField;
        
        private uint maxWhitelistedItemsField;
        
        private uint maxBlacklistedItemsField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public ServiceCapabilities()
        {
            this.clientSuppliedTokenSupportedField = false;
            this.defaultCredentialSuspensionDurationField = "PT5M";
            this.maxWhitelistedItemsField = ((uint)(0));
            this.maxBlacklistedItemsField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedIdentifierType", Order=0)]
        public string[] SupportedIdentifierType
        {
            get
            {
                return this.supportedIdentifierTypeField;
            }
            set
            {
                this.supportedIdentifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ServiceCapabilitiesExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CredentialValiditySupported
        {
            get
            {
                return this.credentialValiditySupportedField;
            }
            set
            {
                this.credentialValiditySupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CredentialAccessProfileValiditySupported
        {
            get
            {
                return this.credentialAccessProfileValiditySupportedField;
            }
            set
            {
                this.credentialAccessProfileValiditySupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ValiditySupportsTimeValue
        {
            get
            {
                return this.validitySupportsTimeValueField;
            }
            set
            {
                this.validitySupportsTimeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxCredentials
        {
            get
            {
                return this.maxCredentialsField;
            }
            set
            {
                this.maxCredentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAccessProfilesPerCredential
        {
            get
            {
                return this.maxAccessProfilesPerCredentialField;
            }
            set
            {
                this.maxAccessProfilesPerCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ResetAntipassbackSupported
        {
            get
            {
                return this.resetAntipassbackSupportedField;
            }
            set
            {
                this.resetAntipassbackSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        [System.ComponentModel.DefaultValueAttribute("PT5M")]
        public string DefaultCredentialSuspensionDuration
        {
            get
            {
                return this.defaultCredentialSuspensionDurationField;
            }
            set
            {
                this.defaultCredentialSuspensionDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint MaxWhitelistedItems
        {
            get
            {
                return this.maxWhitelistedItemsField;
            }
            set
            {
                this.maxWhitelistedItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint MaxBlacklistedItems
        {
            get
            {
                return this.maxBlacklistedItemsField;
            }
            set
            {
                this.maxBlacklistedItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class ServiceCapabilitiesExtension
    {
        
        private string[] supportedExemptionTypeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedExemptionType", Order=0)]
        public string[] SupportedExemptionType
        {
            get
            {
                return this.supportedExemptionTypeField;
            }
            set
            {
                this.supportedExemptionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierItem
    {
        
        private CredentialIdentifierType typeField;
        
        private byte[] valueField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CredentialIdentifierType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary", Order=1)]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierType
    {
        
        private string nameField;
        
        private string formatTypeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FormatType
        {
            get
            {
                return this.formatTypeField;
            }
            set
            {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialDataExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialData
    {
        
        private Credential credentialField;
        
        private CredentialState credentialStateField;
        
        private CredentialDataExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credential Credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CredentialState CredentialState
        {
            get
            {
                return this.credentialStateField;
            }
            set
            {
                this.credentialStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CredentialDataExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class Credential : CredentialInfo
    {
        
        private CredentialIdentifier[] credentialIdentifierField;
        
        private CredentialAccessProfile[] credentialAccessProfileField;
        
        private bool extendedGrantTimeField;
        
        private Attribute[] attributeField;
        
        private CredentialExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttr1Field;
        
        public Credential()
        {
            this.extendedGrantTimeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CredentialIdentifier", Order=0)]
        public CredentialIdentifier[] CredentialIdentifier
        {
            get
            {
                return this.credentialIdentifierField;
            }
            set
            {
                this.credentialIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile", Order=1)]
        public CredentialAccessProfile[] CredentialAccessProfile
        {
            get
            {
                return this.credentialAccessProfileField;
            }
            set
            {
                this.credentialAccessProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendedGrantTime
        {
            get
            {
                return this.extendedGrantTimeField;
            }
            set
            {
                this.extendedGrantTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=3)]
        public Attribute[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CredentialExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr1
        {
            get
            {
                return this.anyAttr1Field;
            }
            set
            {
                this.anyAttr1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifier
    {
        
        private CredentialIdentifierType typeField;
        
        private bool exemptedFromAuthenticationField;
        
        private byte[] valueField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CredentialIdentifierType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ExemptedFromAuthentication
        {
            get
            {
                return this.exemptedFromAuthenticationField;
            }
            set
            {
                this.exemptedFromAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary", Order=2)]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialAccessProfile
    {
        
        private string accessProfileTokenField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessProfileToken
        {
            get
            {
                return this.accessProfileTokenField;
            }
            set
            {
                this.accessProfileTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class Attribute
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string valueField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Credential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialInfo : DataEntity
    {
        
        private string descriptionField;
        
        private string credentialHolderReferenceField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CredentialHolderReference
        {
            get
            {
                return this.credentialHolderReferenceField;
            }
            set
            {
                this.credentialHolderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CredentialInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Credential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialState
    {
        
        private bool enabledField;
        
        private string reasonField;
        
        private AntipassbackState antipassbackStateField;
        
        private CredentialStateExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AntipassbackState AntipassbackState
        {
            get
            {
                return this.antipassbackStateField;
            }
            set
            {
                this.antipassbackStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CredentialStateExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class AntipassbackState
    {
        
        private bool antipassbackViolatedField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AntipassbackViolated
        {
            get
            {
                return this.antipassbackViolatedField;
            }
            set
            {
                this.antipassbackViolatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialStateExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierFormatTypeInfoExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierFormatTypeInfo
    {
        
        private string formatTypeField;
        
        private string descriptionField;
        
        private CredentialIdentifierFormatTypeInfoExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FormatType
        {
            get
            {
                return this.formatTypeField;
            }
            set
            {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CredentialIdentifierFormatTypeInfoExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetSupportedFormatTypes", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetSupportedFormatTypesRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialIdentifierTypeName;
        
        public GetSupportedFormatTypesRequest()
        {
        }
        
        public GetSupportedFormatTypesRequest(string CredentialIdentifierTypeName)
        {
            this.CredentialIdentifierTypeName = CredentialIdentifierTypeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetSupportedFormatTypesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetSupportedFormatTypesResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FormatTypeInfo")]
        public SharpOnvifServer.Credential.CredentialIdentifierFormatTypeInfo[] FormatTypeInfo;
        
        public GetSupportedFormatTypesResponse()
        {
        }
        
        public GetSupportedFormatTypesResponse(SharpOnvifServer.Credential.CredentialIdentifierFormatTypeInfo[] FormatTypeInfo)
        {
            this.FormatTypeInfo = FormatTypeInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialInfo", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetCredentialInfoRequest()
        {
        }
        
        public GetCredentialInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialInfo")]
        public SharpOnvifServer.Credential.CredentialInfo[] CredentialInfo;
        
        public GetCredentialInfoResponse()
        {
        }
        
        public GetCredentialInfoResponse(SharpOnvifServer.Credential.CredentialInfo[] CredentialInfo)
        {
            this.CredentialInfo = CredentialInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialInfoList", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        public GetCredentialInfoListRequest()
        {
        }
        
        public GetCredentialInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialInfo")]
        public SharpOnvifServer.Credential.CredentialInfo[] CredentialInfo;
        
        public GetCredentialInfoListResponse()
        {
        }
        
        public GetCredentialInfoListResponse(string NextStartReference, SharpOnvifServer.Credential.CredentialInfo[] CredentialInfo)
        {
            this.NextStartReference = NextStartReference;
            this.CredentialInfo = CredentialInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentials", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialsRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetCredentialsRequest()
        {
        }
        
        public GetCredentialsRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialsResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialsResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Credential")]
        public SharpOnvifServer.Credential.Credential[] Credential;
        
        public GetCredentialsResponse()
        {
        }
        
        public GetCredentialsResponse(SharpOnvifServer.Credential.Credential[] Credential)
        {
            this.Credential = Credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialList", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        public GetCredentialListRequest()
        {
        }
        
        public GetCredentialListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialListResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Credential")]
        public SharpOnvifServer.Credential.Credential[] Credential;
        
        public GetCredentialListResponse()
        {
        }
        
        public GetCredentialListResponse(string NextStartReference, SharpOnvifServer.Credential.Credential[] Credential)
        {
            this.NextStartReference = NextStartReference;
            this.Credential = Credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialIdentifiers", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialIdentifiersRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        public GetCredentialIdentifiersRequest()
        {
        }
        
        public GetCredentialIdentifiersRequest(string CredentialToken)
        {
            this.CredentialToken = CredentialToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialIdentifiersResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialIdentifiersResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialIdentifier")]
        public SharpOnvifServer.Credential.CredentialIdentifier[] CredentialIdentifier;
        
        public GetCredentialIdentifiersResponse()
        {
        }
        
        public GetCredentialIdentifiersResponse(SharpOnvifServer.Credential.CredentialIdentifier[] CredentialIdentifier)
        {
            this.CredentialIdentifier = CredentialIdentifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialAccessProfilesRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        public GetCredentialAccessProfilesRequest()
        {
        }
        
        public GetCredentialAccessProfilesRequest(string CredentialToken)
        {
            this.CredentialToken = CredentialToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialAccessProfilesResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile")]
        public SharpOnvifServer.Credential.CredentialAccessProfile[] CredentialAccessProfile;
        
        public GetCredentialAccessProfilesResponse()
        {
        }
        
        public GetCredentialAccessProfilesResponse(SharpOnvifServer.Credential.CredentialAccessProfile[] CredentialAccessProfile)
        {
            this.CredentialAccessProfile = CredentialAccessProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="SetCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class SetCredentialAccessProfilesRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile")]
        public SharpOnvifServer.Credential.CredentialAccessProfile[] CredentialAccessProfile;
        
        public SetCredentialAccessProfilesRequest()
        {
        }
        
        public SetCredentialAccessProfilesRequest(string CredentialToken, SharpOnvifServer.Credential.CredentialAccessProfile[] CredentialAccessProfile)
        {
            this.CredentialToken = CredentialToken;
            this.CredentialAccessProfile = CredentialAccessProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="SetCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class SetCredentialAccessProfilesResponse
    {
        
        public SetCredentialAccessProfilesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="DeleteCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class DeleteCredentialAccessProfilesRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfileToken")]
        public string[] AccessProfileToken;
        
        public DeleteCredentialAccessProfilesRequest()
        {
        }
        
        public DeleteCredentialAccessProfilesRequest(string CredentialToken, string[] AccessProfileToken)
        {
            this.CredentialToken = CredentialToken;
            this.AccessProfileToken = AccessProfileToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="DeleteCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class DeleteCredentialAccessProfilesResponse
    {
        
        public DeleteCredentialAccessProfilesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetWhitelistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=2)]
        public string IdentifierType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=3)]
        public string FormatType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Value;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public GetWhitelistRequest()
        {
        }
        
        public GetWhitelistRequest(int Limit, string StartReference, string IdentifierType, string FormatType, byte[] Value, System.Xml.XmlElement[] Any)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
            this.IdentifierType = IdentifierType;
            this.FormatType = FormatType;
            this.Value = Value;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetWhitelistResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        public GetWhitelistResponse()
        {
        }
        
        public GetWhitelistResponse(string NextStartReference, SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier)
        {
            this.NextStartReference = NextStartReference;
            this.Identifier = Identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="AddToWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToWhitelistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public AddToWhitelistRequest()
        {
        }
        
        public AddToWhitelistRequest(SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="AddToWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToWhitelistResponse
    {
        
        public AddToWhitelistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="RemoveFromWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromWhitelistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public RemoveFromWhitelistRequest()
        {
        }
        
        public RemoveFromWhitelistRequest(SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="RemoveFromWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromWhitelistResponse
    {
        
        public RemoveFromWhitelistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetBlacklistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=2)]
        public string IdentifierType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=3)]
        public string FormatType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Value;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public GetBlacklistRequest()
        {
        }
        
        public GetBlacklistRequest(int Limit, string StartReference, string IdentifierType, string FormatType, byte[] Value, System.Xml.XmlElement[] Any)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
            this.IdentifierType = IdentifierType;
            this.FormatType = FormatType;
            this.Value = Value;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetBlacklistResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        public GetBlacklistResponse()
        {
        }
        
        public GetBlacklistResponse(string NextStartReference, SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier)
        {
            this.NextStartReference = NextStartReference;
            this.Identifier = Identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="AddToBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToBlacklistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public AddToBlacklistRequest()
        {
        }
        
        public AddToBlacklistRequest(SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="AddToBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToBlacklistResponse
    {
        
        public AddToBlacklistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="RemoveFromBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromBlacklistRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public RemoveFromBlacklistRequest()
        {
        }
        
        public RemoveFromBlacklistRequest(SharpOnvifServer.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="RemoveFromBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromBlacklistResponse
    {
        
        public RemoveFromBlacklistResponse()
        {
        }
    }
}
