//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpOnvifClient.Credential
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", ConfigurationName="SharpOnvifClient.Credential.CredentialPort")]
    public interface CredentialPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.ServiceCapabilities> GetServiceCapabilitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetSupportedFormatTypesResponse> GetSupportedFormatTypesAsync(SharpOnvifClient.Credential.GetSupportedFormatTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialInfoResponse> GetCredentialInfoAsync(SharpOnvifClient.Credential.GetCredentialInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialInfoListResponse> GetCredentialInfoListAsync(SharpOnvifClient.Credential.GetCredentialInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialsResponse> GetCredentialsAsync(SharpOnvifClient.Credential.GetCredentialsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialListResponse> GetCredentialListAsync(SharpOnvifClient.Credential.GetCredentialListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/CreateCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Token")]
        System.Threading.Tasks.Task<string> CreateCredentialAsync(SharpOnvifClient.Credential.Credential Credential, SharpOnvifClient.Credential.CredentialState State);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task SetCredentialAsync(SharpOnvifClient.Credential.CredentialData CredentialData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/ModifyCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task ModifyCredentialAsync(SharpOnvifClient.Credential.Credential Credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteCredentialAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="State")]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.CredentialState> GetCredentialStateAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/EnableCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task EnableCredentialAsync(string Token, string Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DisableCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DisableCredentialAsync(string Token, string Reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task ResetAntipassbackViolationAsync(string CredentialToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialIdentifiersResponse> GetCredentialIdentifiersAsync(SharpOnvifClient.Credential.GetCredentialIdentifiersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task SetCredentialIdentifierAsync(string CredentialToken, SharpOnvifClient.Credential.CredentialIdentifier CredentialIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteCredentialIdentifierAsync(string CredentialToken, string CredentialIdentifierTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialAccessProfilesResponse> GetCredentialAccessProfilesAsync(SharpOnvifClient.Credential.GetCredentialAccessProfilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.SetCredentialAccessProfilesResponse> SetCredentialAccessProfilesAsync(SharpOnvifClient.Credential.SetCredentialAccessProfilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.DeleteCredentialAccessProfilesResponse> DeleteCredentialAccessProfilesAsync(SharpOnvifClient.Credential.DeleteCredentialAccessProfilesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetWhitelist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetWhitelistResponse> GetWhitelistAsync(SharpOnvifClient.Credential.GetWhitelistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/AddToWhitelist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToWhitelistResponse> AddToWhitelistAsync(SharpOnvifClient.Credential.AddToWhitelistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/RemoveFromWhitelist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromWhitelistResponse> RemoveFromWhitelistAsync(SharpOnvifClient.Credential.RemoveFromWhitelistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteWhitelist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteWhitelistAsync();
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/GetBlacklist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetBlacklistResponse> GetBlacklistAsync(SharpOnvifClient.Credential.GetBlacklistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/AddToBlacklist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToBlacklistResponse> AddToBlacklistAsync(SharpOnvifClient.Credential.AddToBlacklistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/RemoveFromBlacklist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromBlacklistResponse> RemoveFromBlacklistAsync(SharpOnvifClient.Credential.RemoveFromBlacklistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/credential/wsdl/DeleteBlacklist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteBlacklistAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class ServiceCapabilities
    {
        
        private string[] supportedIdentifierTypeField;
        
        private ServiceCapabilitiesExtension extensionField;
        
        private uint maxLimitField;
        
        private bool credentialValiditySupportedField;
        
        private bool credentialAccessProfileValiditySupportedField;
        
        private bool validitySupportsTimeValueField;
        
        private uint maxCredentialsField;
        
        private uint maxAccessProfilesPerCredentialField;
        
        private bool resetAntipassbackSupportedField;
        
        private bool clientSuppliedTokenSupportedField;
        
        private string defaultCredentialSuspensionDurationField;
        
        private uint maxWhitelistedItemsField;
        
        private uint maxBlacklistedItemsField;
        
        public ServiceCapabilities()
        {
            this.clientSuppliedTokenSupportedField = false;
            this.defaultCredentialSuspensionDurationField = "PT5M";
            this.maxWhitelistedItemsField = ((uint)(0));
            this.maxBlacklistedItemsField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedIdentifierType", Order=0)]
        public string[] SupportedIdentifierType
        {
            get
            {
                return this.supportedIdentifierTypeField;
            }
            set
            {
                this.supportedIdentifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ServiceCapabilitiesExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CredentialValiditySupported
        {
            get
            {
                return this.credentialValiditySupportedField;
            }
            set
            {
                this.credentialValiditySupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CredentialAccessProfileValiditySupported
        {
            get
            {
                return this.credentialAccessProfileValiditySupportedField;
            }
            set
            {
                this.credentialAccessProfileValiditySupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ValiditySupportsTimeValue
        {
            get
            {
                return this.validitySupportsTimeValueField;
            }
            set
            {
                this.validitySupportsTimeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxCredentials
        {
            get
            {
                return this.maxCredentialsField;
            }
            set
            {
                this.maxCredentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAccessProfilesPerCredential
        {
            get
            {
                return this.maxAccessProfilesPerCredentialField;
            }
            set
            {
                this.maxAccessProfilesPerCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ResetAntipassbackSupported
        {
            get
            {
                return this.resetAntipassbackSupportedField;
            }
            set
            {
                this.resetAntipassbackSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        [System.ComponentModel.DefaultValueAttribute("PT5M")]
        public string DefaultCredentialSuspensionDuration
        {
            get
            {
                return this.defaultCredentialSuspensionDurationField;
            }
            set
            {
                this.defaultCredentialSuspensionDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint MaxWhitelistedItems
        {
            get
            {
                return this.maxWhitelistedItemsField;
            }
            set
            {
                this.maxWhitelistedItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint MaxBlacklistedItems
        {
            get
            {
                return this.maxBlacklistedItemsField;
            }
            set
            {
                this.maxBlacklistedItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class ServiceCapabilitiesExtension
    {
        
        private string[] supportedExemptionTypeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedExemptionType", Order=0)]
        public string[] SupportedExemptionType
        {
            get
            {
                return this.supportedExemptionTypeField;
            }
            set
            {
                this.supportedExemptionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierItem
    {
        
        private CredentialIdentifierType typeField;
        
        private byte[] valueField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CredentialIdentifierType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary", Order=1)]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierType
    {
        
        private string nameField;
        
        private string formatTypeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FormatType
        {
            get
            {
                return this.formatTypeField;
            }
            set
            {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialDataExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialData
    {
        
        private Credential credentialField;
        
        private CredentialState credentialStateField;
        
        private CredentialDataExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credential Credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CredentialState CredentialState
        {
            get
            {
                return this.credentialStateField;
            }
            set
            {
                this.credentialStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CredentialDataExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class Credential : CredentialInfo
    {
        
        private CredentialIdentifier[] credentialIdentifierField;
        
        private CredentialAccessProfile[] credentialAccessProfileField;
        
        private bool extendedGrantTimeField;
        
        private Attribute[] attributeField;
        
        private CredentialExtension extensionField;
        
        public Credential()
        {
            this.extendedGrantTimeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CredentialIdentifier", Order=0)]
        public CredentialIdentifier[] CredentialIdentifier
        {
            get
            {
                return this.credentialIdentifierField;
            }
            set
            {
                this.credentialIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile", Order=1)]
        public CredentialAccessProfile[] CredentialAccessProfile
        {
            get
            {
                return this.credentialAccessProfileField;
            }
            set
            {
                this.credentialAccessProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendedGrantTime
        {
            get
            {
                return this.extendedGrantTimeField;
            }
            set
            {
                this.extendedGrantTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=3)]
        public Attribute[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CredentialExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifier
    {
        
        private CredentialIdentifierType typeField;
        
        private bool exemptedFromAuthenticationField;
        
        private byte[] valueField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CredentialIdentifierType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ExemptedFromAuthentication
        {
            get
            {
                return this.exemptedFromAuthenticationField;
            }
            set
            {
                this.exemptedFromAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary", Order=2)]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialAccessProfile
    {
        
        private string accessProfileTokenField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessProfileToken
        {
            get
            {
                return this.accessProfileTokenField;
            }
            set
            {
                this.accessProfileTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class Attribute
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Credential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialInfo : DataEntity
    {
        
        private string descriptionField;
        
        private string credentialHolderReferenceField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CredentialHolderReference
        {
            get
            {
                return this.credentialHolderReferenceField;
            }
            set
            {
                this.credentialHolderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CredentialInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Credential))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialState
    {
        
        private bool enabledField;
        
        private string reasonField;
        
        private AntipassbackState antipassbackStateField;
        
        private CredentialStateExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AntipassbackState AntipassbackState
        {
            get
            {
                return this.antipassbackStateField;
            }
            set
            {
                this.antipassbackStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CredentialStateExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class AntipassbackState
    {
        
        private bool antipassbackViolatedField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AntipassbackViolated
        {
            get
            {
                return this.antipassbackViolatedField;
            }
            set
            {
                this.antipassbackViolatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialStateExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierFormatTypeInfoExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl")]
    public partial class CredentialIdentifierFormatTypeInfo
    {
        
        private string formatTypeField;
        
        private string descriptionField;
        
        private CredentialIdentifierFormatTypeInfoExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FormatType
        {
            get
            {
                return this.formatTypeField;
            }
            set
            {
                this.formatTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CredentialIdentifierFormatTypeInfoExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedFormatTypes", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetSupportedFormatTypesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialIdentifierTypeName;
        
        public GetSupportedFormatTypesRequest()
        {
        }
        
        public GetSupportedFormatTypesRequest(string CredentialIdentifierTypeName)
        {
            this.CredentialIdentifierTypeName = CredentialIdentifierTypeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedFormatTypesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetSupportedFormatTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FormatTypeInfo")]
        public SharpOnvifClient.Credential.CredentialIdentifierFormatTypeInfo[] FormatTypeInfo;
        
        public GetSupportedFormatTypesResponse()
        {
        }
        
        public GetSupportedFormatTypesResponse(SharpOnvifClient.Credential.CredentialIdentifierFormatTypeInfo[] FormatTypeInfo)
        {
            this.FormatTypeInfo = FormatTypeInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialInfo", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetCredentialInfoRequest()
        {
        }
        
        public GetCredentialInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialInfo")]
        public SharpOnvifClient.Credential.CredentialInfo[] CredentialInfo;
        
        public GetCredentialInfoResponse()
        {
        }
        
        public GetCredentialInfoResponse(SharpOnvifClient.Credential.CredentialInfo[] CredentialInfo)
        {
            this.CredentialInfo = CredentialInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialInfoList", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        public GetCredentialInfoListRequest()
        {
        }
        
        public GetCredentialInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialInfoListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialInfo")]
        public SharpOnvifClient.Credential.CredentialInfo[] CredentialInfo;
        
        public GetCredentialInfoListResponse()
        {
        }
        
        public GetCredentialInfoListResponse(string NextStartReference, SharpOnvifClient.Credential.CredentialInfo[] CredentialInfo)
        {
            this.NextStartReference = NextStartReference;
            this.CredentialInfo = CredentialInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentials", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetCredentialsRequest()
        {
        }
        
        public GetCredentialsRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialsResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Credential")]
        public SharpOnvifClient.Credential.Credential[] Credential;
        
        public GetCredentialsResponse()
        {
        }
        
        public GetCredentialsResponse(SharpOnvifClient.Credential.Credential[] Credential)
        {
            this.Credential = Credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialList", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        public GetCredentialListRequest()
        {
        }
        
        public GetCredentialListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialListResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Credential")]
        public SharpOnvifClient.Credential.Credential[] Credential;
        
        public GetCredentialListResponse()
        {
        }
        
        public GetCredentialListResponse(string NextStartReference, SharpOnvifClient.Credential.Credential[] Credential)
        {
            this.NextStartReference = NextStartReference;
            this.Credential = Credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialIdentifiers", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialIdentifiersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        public GetCredentialIdentifiersRequest()
        {
        }
        
        public GetCredentialIdentifiersRequest(string CredentialToken)
        {
            this.CredentialToken = CredentialToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialIdentifiersResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialIdentifiersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialIdentifier")]
        public SharpOnvifClient.Credential.CredentialIdentifier[] CredentialIdentifier;
        
        public GetCredentialIdentifiersResponse()
        {
        }
        
        public GetCredentialIdentifiersResponse(SharpOnvifClient.Credential.CredentialIdentifier[] CredentialIdentifier)
        {
            this.CredentialIdentifier = CredentialIdentifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialAccessProfilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        public GetCredentialAccessProfilesRequest()
        {
        }
        
        public GetCredentialAccessProfilesRequest(string CredentialToken)
        {
            this.CredentialToken = CredentialToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetCredentialAccessProfilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile")]
        public SharpOnvifClient.Credential.CredentialAccessProfile[] CredentialAccessProfile;
        
        public GetCredentialAccessProfilesResponse()
        {
        }
        
        public GetCredentialAccessProfilesResponse(SharpOnvifClient.Credential.CredentialAccessProfile[] CredentialAccessProfile)
        {
            this.CredentialAccessProfile = CredentialAccessProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class SetCredentialAccessProfilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("CredentialAccessProfile")]
        public SharpOnvifClient.Credential.CredentialAccessProfile[] CredentialAccessProfile;
        
        public SetCredentialAccessProfilesRequest()
        {
        }
        
        public SetCredentialAccessProfilesRequest(string CredentialToken, SharpOnvifClient.Credential.CredentialAccessProfile[] CredentialAccessProfile)
        {
            this.CredentialToken = CredentialToken;
            this.CredentialAccessProfile = CredentialAccessProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class SetCredentialAccessProfilesResponse
    {
        
        public SetCredentialAccessProfilesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCredentialAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class DeleteCredentialAccessProfilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string CredentialToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfileToken")]
        public string[] AccessProfileToken;
        
        public DeleteCredentialAccessProfilesRequest()
        {
        }
        
        public DeleteCredentialAccessProfilesRequest(string CredentialToken, string[] AccessProfileToken)
        {
            this.CredentialToken = CredentialToken;
            this.AccessProfileToken = AccessProfileToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCredentialAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class DeleteCredentialAccessProfilesResponse
    {
        
        public DeleteCredentialAccessProfilesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetWhitelistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=2)]
        public string IdentifierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=3)]
        public string FormatType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public GetWhitelistRequest()
        {
        }
        
        public GetWhitelistRequest(int Limit, string StartReference, string IdentifierType, string FormatType, byte[] Value, System.Xml.XmlElement[] Any)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
            this.IdentifierType = IdentifierType;
            this.FormatType = FormatType;
            this.Value = Value;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetWhitelistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        public GetWhitelistResponse()
        {
        }
        
        public GetWhitelistResponse(string NextStartReference, SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier)
        {
            this.NextStartReference = NextStartReference;
            this.Identifier = Identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToWhitelistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public AddToWhitelistRequest()
        {
        }
        
        public AddToWhitelistRequest(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToWhitelistResponse
    {
        
        public AddToWhitelistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveFromWhitelist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromWhitelistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public RemoveFromWhitelistRequest()
        {
        }
        
        public RemoveFromWhitelistRequest(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveFromWhitelistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromWhitelistResponse
    {
        
        public RemoveFromWhitelistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetBlacklistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        public string StartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=2)]
        public string IdentifierType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=3)]
        public string FormatType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public GetBlacklistRequest()
        {
        }
        
        public GetBlacklistRequest(int Limit, string StartReference, string IdentifierType, string FormatType, byte[] Value, System.Xml.XmlElement[] Any)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
            this.IdentifierType = IdentifierType;
            this.FormatType = FormatType;
            this.Value = Value;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class GetBlacklistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        public GetBlacklistResponse()
        {
        }
        
        public GetBlacklistResponse(string NextStartReference, SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier)
        {
            this.NextStartReference = NextStartReference;
            this.Identifier = Identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToBlacklistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public AddToBlacklistRequest()
        {
        }
        
        public AddToBlacklistRequest(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class AddToBlacklistResponse
    {
        
        public AddToBlacklistResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveFromBlacklist", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromBlacklistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/credential/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public RemoveFromBlacklistRequest()
        {
        }
        
        public RemoveFromBlacklistRequest(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            this.Identifier = Identifier;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveFromBlacklistResponse", WrapperNamespace="http://www.onvif.org/ver10/credential/wsdl", IsWrapped=true)]
    public partial class RemoveFromBlacklistResponse
    {
        
        public RemoveFromBlacklistResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CredentialPortChannel : SharpOnvifClient.Credential.CredentialPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CredentialPortClient : System.ServiceModel.ClientBase<SharpOnvifClient.Credential.CredentialPort>, SharpOnvifClient.Credential.CredentialPort
    {
        
        public CredentialPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.ServiceCapabilities> GetServiceCapabilitiesAsync()
        {
            return base.Channel.GetServiceCapabilitiesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetSupportedFormatTypesResponse> SharpOnvifClient.Credential.CredentialPort.GetSupportedFormatTypesAsync(SharpOnvifClient.Credential.GetSupportedFormatTypesRequest request)
        {
            return base.Channel.GetSupportedFormatTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetSupportedFormatTypesResponse> GetSupportedFormatTypesAsync(string CredentialIdentifierTypeName)
        {
            SharpOnvifClient.Credential.GetSupportedFormatTypesRequest inValue = new SharpOnvifClient.Credential.GetSupportedFormatTypesRequest();
            inValue.CredentialIdentifierTypeName = CredentialIdentifierTypeName;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).GetSupportedFormatTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialInfoResponse> SharpOnvifClient.Credential.CredentialPort.GetCredentialInfoAsync(SharpOnvifClient.Credential.GetCredentialInfoRequest request)
        {
            return base.Channel.GetCredentialInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialInfoResponse> GetCredentialInfoAsync(string[] Token)
        {
            SharpOnvifClient.Credential.GetCredentialInfoRequest inValue = new SharpOnvifClient.Credential.GetCredentialInfoRequest();
            inValue.Token = Token;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).GetCredentialInfoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialInfoListResponse> GetCredentialInfoListAsync(SharpOnvifClient.Credential.GetCredentialInfoListRequest request)
        {
            return base.Channel.GetCredentialInfoListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialsResponse> SharpOnvifClient.Credential.CredentialPort.GetCredentialsAsync(SharpOnvifClient.Credential.GetCredentialsRequest request)
        {
            return base.Channel.GetCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialsResponse> GetCredentialsAsync(string[] Token)
        {
            SharpOnvifClient.Credential.GetCredentialsRequest inValue = new SharpOnvifClient.Credential.GetCredentialsRequest();
            inValue.Token = Token;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).GetCredentialsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialListResponse> GetCredentialListAsync(SharpOnvifClient.Credential.GetCredentialListRequest request)
        {
            return base.Channel.GetCredentialListAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> CreateCredentialAsync(SharpOnvifClient.Credential.Credential Credential, SharpOnvifClient.Credential.CredentialState State)
        {
            return base.Channel.CreateCredentialAsync(Credential, State);
        }
        
        public System.Threading.Tasks.Task SetCredentialAsync(SharpOnvifClient.Credential.CredentialData CredentialData)
        {
            return base.Channel.SetCredentialAsync(CredentialData);
        }
        
        public System.Threading.Tasks.Task ModifyCredentialAsync(SharpOnvifClient.Credential.Credential Credential)
        {
            return base.Channel.ModifyCredentialAsync(Credential);
        }
        
        public System.Threading.Tasks.Task DeleteCredentialAsync(string Token)
        {
            return base.Channel.DeleteCredentialAsync(Token);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.CredentialState> GetCredentialStateAsync(string Token)
        {
            return base.Channel.GetCredentialStateAsync(Token);
        }
        
        public System.Threading.Tasks.Task EnableCredentialAsync(string Token, string Reason)
        {
            return base.Channel.EnableCredentialAsync(Token, Reason);
        }
        
        public System.Threading.Tasks.Task DisableCredentialAsync(string Token, string Reason)
        {
            return base.Channel.DisableCredentialAsync(Token, Reason);
        }
        
        public System.Threading.Tasks.Task ResetAntipassbackViolationAsync(string CredentialToken)
        {
            return base.Channel.ResetAntipassbackViolationAsync(CredentialToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialIdentifiersResponse> SharpOnvifClient.Credential.CredentialPort.GetCredentialIdentifiersAsync(SharpOnvifClient.Credential.GetCredentialIdentifiersRequest request)
        {
            return base.Channel.GetCredentialIdentifiersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialIdentifiersResponse> GetCredentialIdentifiersAsync(string CredentialToken)
        {
            SharpOnvifClient.Credential.GetCredentialIdentifiersRequest inValue = new SharpOnvifClient.Credential.GetCredentialIdentifiersRequest();
            inValue.CredentialToken = CredentialToken;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).GetCredentialIdentifiersAsync(inValue);
        }
        
        public System.Threading.Tasks.Task SetCredentialIdentifierAsync(string CredentialToken, SharpOnvifClient.Credential.CredentialIdentifier CredentialIdentifier)
        {
            return base.Channel.SetCredentialIdentifierAsync(CredentialToken, CredentialIdentifier);
        }
        
        public System.Threading.Tasks.Task DeleteCredentialIdentifierAsync(string CredentialToken, string CredentialIdentifierTypeName)
        {
            return base.Channel.DeleteCredentialIdentifierAsync(CredentialToken, CredentialIdentifierTypeName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialAccessProfilesResponse> SharpOnvifClient.Credential.CredentialPort.GetCredentialAccessProfilesAsync(SharpOnvifClient.Credential.GetCredentialAccessProfilesRequest request)
        {
            return base.Channel.GetCredentialAccessProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetCredentialAccessProfilesResponse> GetCredentialAccessProfilesAsync(string CredentialToken)
        {
            SharpOnvifClient.Credential.GetCredentialAccessProfilesRequest inValue = new SharpOnvifClient.Credential.GetCredentialAccessProfilesRequest();
            inValue.CredentialToken = CredentialToken;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).GetCredentialAccessProfilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.SetCredentialAccessProfilesResponse> SharpOnvifClient.Credential.CredentialPort.SetCredentialAccessProfilesAsync(SharpOnvifClient.Credential.SetCredentialAccessProfilesRequest request)
        {
            return base.Channel.SetCredentialAccessProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.SetCredentialAccessProfilesResponse> SetCredentialAccessProfilesAsync(string CredentialToken, SharpOnvifClient.Credential.CredentialAccessProfile[] CredentialAccessProfile)
        {
            SharpOnvifClient.Credential.SetCredentialAccessProfilesRequest inValue = new SharpOnvifClient.Credential.SetCredentialAccessProfilesRequest();
            inValue.CredentialToken = CredentialToken;
            inValue.CredentialAccessProfile = CredentialAccessProfile;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).SetCredentialAccessProfilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.DeleteCredentialAccessProfilesResponse> SharpOnvifClient.Credential.CredentialPort.DeleteCredentialAccessProfilesAsync(SharpOnvifClient.Credential.DeleteCredentialAccessProfilesRequest request)
        {
            return base.Channel.DeleteCredentialAccessProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.DeleteCredentialAccessProfilesResponse> DeleteCredentialAccessProfilesAsync(string CredentialToken, string[] AccessProfileToken)
        {
            SharpOnvifClient.Credential.DeleteCredentialAccessProfilesRequest inValue = new SharpOnvifClient.Credential.DeleteCredentialAccessProfilesRequest();
            inValue.CredentialToken = CredentialToken;
            inValue.AccessProfileToken = AccessProfileToken;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).DeleteCredentialAccessProfilesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetWhitelistResponse> GetWhitelistAsync(SharpOnvifClient.Credential.GetWhitelistRequest request)
        {
            return base.Channel.GetWhitelistAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToWhitelistResponse> SharpOnvifClient.Credential.CredentialPort.AddToWhitelistAsync(SharpOnvifClient.Credential.AddToWhitelistRequest request)
        {
            return base.Channel.AddToWhitelistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToWhitelistResponse> AddToWhitelistAsync(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            SharpOnvifClient.Credential.AddToWhitelistRequest inValue = new SharpOnvifClient.Credential.AddToWhitelistRequest();
            inValue.Identifier = Identifier;
            inValue.Any = Any;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).AddToWhitelistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromWhitelistResponse> SharpOnvifClient.Credential.CredentialPort.RemoveFromWhitelistAsync(SharpOnvifClient.Credential.RemoveFromWhitelistRequest request)
        {
            return base.Channel.RemoveFromWhitelistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromWhitelistResponse> RemoveFromWhitelistAsync(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            SharpOnvifClient.Credential.RemoveFromWhitelistRequest inValue = new SharpOnvifClient.Credential.RemoveFromWhitelistRequest();
            inValue.Identifier = Identifier;
            inValue.Any = Any;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).RemoveFromWhitelistAsync(inValue);
        }
        
        public System.Threading.Tasks.Task DeleteWhitelistAsync()
        {
            return base.Channel.DeleteWhitelistAsync();
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.GetBlacklistResponse> GetBlacklistAsync(SharpOnvifClient.Credential.GetBlacklistRequest request)
        {
            return base.Channel.GetBlacklistAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToBlacklistResponse> SharpOnvifClient.Credential.CredentialPort.AddToBlacklistAsync(SharpOnvifClient.Credential.AddToBlacklistRequest request)
        {
            return base.Channel.AddToBlacklistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.AddToBlacklistResponse> AddToBlacklistAsync(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            SharpOnvifClient.Credential.AddToBlacklistRequest inValue = new SharpOnvifClient.Credential.AddToBlacklistRequest();
            inValue.Identifier = Identifier;
            inValue.Any = Any;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).AddToBlacklistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromBlacklistResponse> SharpOnvifClient.Credential.CredentialPort.RemoveFromBlacklistAsync(SharpOnvifClient.Credential.RemoveFromBlacklistRequest request)
        {
            return base.Channel.RemoveFromBlacklistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharpOnvifClient.Credential.RemoveFromBlacklistResponse> RemoveFromBlacklistAsync(SharpOnvifClient.Credential.CredentialIdentifierItem[] Identifier, System.Xml.XmlElement[] Any)
        {
            SharpOnvifClient.Credential.RemoveFromBlacklistRequest inValue = new SharpOnvifClient.Credential.RemoveFromBlacklistRequest();
            inValue.Identifier = Identifier;
            inValue.Any = Any;
            return ((SharpOnvifClient.Credential.CredentialPort)(this)).RemoveFromBlacklistAsync(inValue);
        }
        
        public System.Threading.Tasks.Task DeleteBlacklistAsync()
        {
            return base.Channel.DeleteBlacklistAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
