//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnvifScAccessControl
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", ConfigurationName="OnvifScAccessControl.PACSPort")]
    public interface PACSPort
    {
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetServiceCapabilities")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Capabilities")]
        OnvifScAccessControl.ServiceCapabilities GetServiceCapabilities();
        
        // CODEGEN: Parameter 'AccessPointInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointInfo")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AccessPointInfo")]
        OnvifScAccessControl.GetAccessPointInfoResponse GetAccessPointInfo(OnvifScAccessControl.GetAccessPointInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointInfoList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessControl.GetAccessPointInfoListResponse GetAccessPointInfoList(OnvifScAccessControl.GetAccessPointInfoListRequest request);
        
        // CODEGEN: Parameter 'AccessPoint' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPoints")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AccessPoint")]
        OnvifScAccessControl.GetAccessPointsResponse GetAccessPoints(OnvifScAccessControl.GetAccessPointsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessControl.GetAccessPointListResponse GetAccessPointList(OnvifScAccessControl.GetAccessPointListRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/CreateAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Token")]
        string CreateAccessPoint(OnvifScAccessControl.AccessPoint AccessPoint);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/SetAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetAccessPoint(OnvifScAccessControl.AccessPoint AccessPoint);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/ModifyAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ModifyAccessPoint(OnvifScAccessControl.AccessPoint AccessPoint);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/DeleteAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteAccessPoint(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/SetAccessPointAuthenticationProfile" +
            "")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetAccessPointAuthenticationProfile(string Token, string AuthenticationProfileToken);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/DeleteAccessPointAuthenticationProf" +
            "ile")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteAccessPointAuthenticationProfile(string Token);
        
        // CODEGEN: Parameter 'AreaInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaInfo")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AreaInfo")]
        OnvifScAccessControl.GetAreaInfoResponse GetAreaInfo(OnvifScAccessControl.GetAreaInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaInfoList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessControl.GetAreaInfoListResponse GetAreaInfoList(OnvifScAccessControl.GetAreaInfoListRequest request);
        
        // CODEGEN: Parameter 'Area' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreas")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Area")]
        OnvifScAccessControl.GetAreasResponse GetAreas(OnvifScAccessControl.GetAreasRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAreaList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessControl.GetAreaListResponse GetAreaList(OnvifScAccessControl.GetAreaListRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/CreateArea")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Token")]
        string CreateArea(OnvifScAccessControl.Area Area);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/SetArea")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetArea(OnvifScAccessControl.Area Area);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/ModifyArea")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ModifyArea(OnvifScAccessControl.Area Area);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/DeleteArea")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteArea(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/GetAccessPointState")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AccessPointState")]
        OnvifScAccessControl.AccessPointState GetAccessPointState(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/EnableAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void EnableAccessPoint(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/DisableAccessPoint")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DisableAccessPoint(string Token);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/ExternalAuthorization")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ExternalAuthorization(string AccessPointToken, string CredentialToken, string Reason, OnvifScAccessControl.Decision Decision);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accesscontrol/wsdl/Feedback")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessControl.FeedbackResponse Feedback(OnvifScAccessControl.FeedbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class ServiceCapabilities
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private uint maxLimitField;
        
        private uint maxAccessPointsField;
        
        private uint maxAreasField;
        
        private bool clientSuppliedTokenSupportedField;
        
        private bool accessPointManagementSupportedField;
        
        private bool areaManagementSupportedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public ServiceCapabilities()
        {
            this.maxAccessPointsField = ((uint)(10));
            this.maxAreasField = ((uint)(10));
            this.clientSuppliedTokenSupportedField = false;
            this.accessPointManagementSupportedField = false;
            this.areaManagementSupportedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "10")]
        public uint MaxAccessPoints
        {
            get
            {
                return this.maxAccessPointsField;
            }
            set
            {
                this.maxAccessPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "10")]
        public uint MaxAreas
        {
            get
            {
                return this.maxAreasField;
            }
            set
            {
                this.maxAreasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AccessPointManagementSupported
        {
            get
            {
                return this.accessPointManagementSupportedField;
            }
            set
            {
                this.accessPointManagementSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AreaManagementSupported
        {
            get
            {
                return this.areaManagementSupportedField;
            }
            set
            {
                this.areaManagementSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointState
    {
        
        private bool enabledField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AreaExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class SupportedSecurityLevelsExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointCapabilities
    {
        
        private string[] supportedSecurityLevelsField;
        
        private SupportedSecurityLevelsExtension extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private bool disableAccessPointField;
        
        private bool duressField;
        
        private bool duressFieldSpecified;
        
        private bool anonymousAccessField;
        
        private bool anonymousAccessFieldSpecified;
        
        private bool accessTakenField;
        
        private bool accessTakenFieldSpecified;
        
        private bool externalAuthorizationField;
        
        private bool externalAuthorizationFieldSpecified;
        
        private string[] supportedRecognitionTypesField;
        
        private bool identifierAccessField;
        
        private bool identifierAccessFieldSpecified;
        
        private string[] supportedFeedbackTypesField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedSecurityLevels", Order=0)]
        public string[] SupportedSecurityLevels
        {
            get
            {
                return this.supportedSecurityLevelsField;
            }
            set
            {
                this.supportedSecurityLevelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SupportedSecurityLevelsExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DisableAccessPoint
        {
            get
            {
                return this.disableAccessPointField;
            }
            set
            {
                this.disableAccessPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Duress
        {
            get
            {
                return this.duressField;
            }
            set
            {
                this.duressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuressSpecified
        {
            get
            {
                return this.duressFieldSpecified;
            }
            set
            {
                this.duressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AnonymousAccess
        {
            get
            {
                return this.anonymousAccessField;
            }
            set
            {
                this.anonymousAccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnonymousAccessSpecified
        {
            get
            {
                return this.anonymousAccessFieldSpecified;
            }
            set
            {
                this.anonymousAccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AccessTaken
        {
            get
            {
                return this.accessTakenField;
            }
            set
            {
                this.accessTakenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessTakenSpecified
        {
            get
            {
                return this.accessTakenFieldSpecified;
            }
            set
            {
                this.accessTakenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ExternalAuthorization
        {
            get
            {
                return this.externalAuthorizationField;
            }
            set
            {
                this.externalAuthorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExternalAuthorizationSpecified
        {
            get
            {
                return this.externalAuthorizationFieldSpecified;
            }
            set
            {
                this.externalAuthorizationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] SupportedRecognitionTypes
        {
            get
            {
                return this.supportedRecognitionTypesField;
            }
            set
            {
                this.supportedRecognitionTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IdentifierAccess
        {
            get
            {
                return this.identifierAccessField;
            }
            set
            {
                this.identifierAccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentifierAccessSpecified
        {
            get
            {
                return this.identifierAccessFieldSpecified;
            }
            set
            {
                this.identifierAccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] SupportedFeedbackTypes
        {
            get
            {
                return this.supportedFeedbackTypesField;
            }
            set
            {
                this.supportedFeedbackTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Area))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfoBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPoint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Area))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AreaInfoBase : DataEntity
    {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Area))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AreaInfo : AreaInfoBase
    {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class Area : AreaInfo
    {
        
        private AreaExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttr1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AreaExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr1
        {
            get
            {
                return this.anyAttr1Field;
            }
            set
            {
                this.anyAttr1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPointInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPoint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointInfoBase : DataEntity
    {
        
        private string nameField;
        
        private string descriptionField;
        
        private string areaFromField;
        
        private string areaToField;
        
        private System.Xml.XmlQualifiedName entityTypeField;
        
        private string entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AreaFrom
        {
            get
            {
                return this.areaFromField;
            }
            set
            {
                this.areaFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AreaTo
        {
            get
            {
                return this.areaToField;
            }
            set
            {
                this.areaToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Xml.XmlQualifiedName EntityType
        {
            get
            {
                return this.entityTypeField;
            }
            set
            {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessPoint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPointInfo : AccessPointInfoBase
    {
        
        private AccessPointCapabilities capabilitiesField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccessPointCapabilities Capabilities
        {
            get
            {
                return this.capabilitiesField;
            }
            set
            {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public partial class AccessPoint : AccessPointInfo
    {
        
        private string authenticationProfileTokenField;
        
        private AccessPointExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttr1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationProfileToken
        {
            get
            {
                return this.authenticationProfileTokenField;
            }
            set
            {
                this.authenticationProfileTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccessPointExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr1
        {
            get
            {
                return this.anyAttr1Field;
            }
            set
            {
                this.anyAttr1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointInfo", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointInfoRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAccessPointInfoRequest()
        {
        }
        
        public GetAccessPointInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointInfoResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AccessPointInfo")]
        public OnvifScAccessControl.AccessPointInfo[] AccessPointInfo;
        
        public GetAccessPointInfoResponse()
        {
        }
        
        public GetAccessPointInfoResponse(OnvifScAccessControl.AccessPointInfo[] AccessPointInfo)
        {
            this.AccessPointInfo = AccessPointInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointInfoList", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointInfoListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        public string StartReference;
        
        public GetAccessPointInfoListRequest()
        {
        }
        
        public GetAccessPointInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointInfoListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessPointInfo")]
        public OnvifScAccessControl.AccessPointInfo[] AccessPointInfo;
        
        public GetAccessPointInfoListResponse()
        {
        }
        
        public GetAccessPointInfoListResponse(string NextStartReference, OnvifScAccessControl.AccessPointInfo[] AccessPointInfo)
        {
            this.NextStartReference = NextStartReference;
            this.AccessPointInfo = AccessPointInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPoints", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointsRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAccessPointsRequest()
        {
        }
        
        public GetAccessPointsRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointsResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointsResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AccessPoint")]
        public OnvifScAccessControl.AccessPoint[] AccessPoint;
        
        public GetAccessPointsResponse()
        {
        }
        
        public GetAccessPointsResponse(OnvifScAccessControl.AccessPoint[] AccessPoint)
        {
            this.AccessPoint = AccessPoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointList", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        public string StartReference;
        
        public GetAccessPointListRequest()
        {
        }
        
        public GetAccessPointListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessPointListResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAccessPointListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessPoint")]
        public OnvifScAccessControl.AccessPoint[] AccessPoint;
        
        public GetAccessPointListResponse()
        {
        }
        
        public GetAccessPointListResponse(string NextStartReference, OnvifScAccessControl.AccessPoint[] AccessPoint)
        {
            this.NextStartReference = NextStartReference;
            this.AccessPoint = AccessPoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaInfo", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaInfoRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAreaInfoRequest()
        {
        }
        
        public GetAreaInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaInfoResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AreaInfo")]
        public OnvifScAccessControl.AreaInfo[] AreaInfo;
        
        public GetAreaInfoResponse()
        {
        }
        
        public GetAreaInfoResponse(OnvifScAccessControl.AreaInfo[] AreaInfo)
        {
            this.AreaInfo = AreaInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaInfoList", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaInfoListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        public string StartReference;
        
        public GetAreaInfoListRequest()
        {
        }
        
        public GetAreaInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaInfoListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AreaInfo")]
        public OnvifScAccessControl.AreaInfo[] AreaInfo;
        
        public GetAreaInfoListResponse()
        {
        }
        
        public GetAreaInfoListResponse(string NextStartReference, OnvifScAccessControl.AreaInfo[] AreaInfo)
        {
            this.NextStartReference = NextStartReference;
            this.AreaInfo = AreaInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreas", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreasRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAreasRequest()
        {
        }
        
        public GetAreasRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreasResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreasResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Area")]
        public OnvifScAccessControl.Area[] Area;
        
        public GetAreasResponse()
        {
        }
        
        public GetAreasResponse(OnvifScAccessControl.Area[] Area)
        {
            this.Area = Area;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaList", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        public string StartReference;
        
        public GetAreaListRequest()
        {
        }
        
        public GetAreaListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAreaListResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class GetAreaListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Area")]
        public OnvifScAccessControl.Area[] Area;
        
        public GetAreaListResponse()
        {
        }
        
        public GetAreaListResponse(string NextStartReference, OnvifScAccessControl.Area[] Area)
        {
            this.NextStartReference = NextStartReference;
            this.Area = Area;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl")]
    public enum Decision
    {
        
        /// <remarks/>
        Granted,
        
        /// <remarks/>
        Denied,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="Feedback", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class FeedbackRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=0)]
        public string AccessPointToken;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=1)]
        public string FeedbackType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("RecognitionType")]
        public string[] RecognitionType;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accesscontrol/wsdl", Order=3)]
        public string TextMessage;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public FeedbackRequest()
        {
        }
        
        public FeedbackRequest(string AccessPointToken, string FeedbackType, string[] RecognitionType, string TextMessage, System.Xml.XmlElement[] Any)
        {
            this.AccessPointToken = AccessPointToken;
            this.FeedbackType = FeedbackType;
            this.RecognitionType = RecognitionType;
            this.TextMessage = TextMessage;
            this.Any = Any;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="FeedbackResponse", WrapperNamespace="http://www.onvif.org/ver10/accesscontrol/wsdl", IsWrapped=true)]
    public partial class FeedbackResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public FeedbackResponse()
        {
        }
        
        public FeedbackResponse(System.Xml.XmlElement[] Any)
        {
            this.Any = Any;
        }
    }
}
