using WsdlGenerator.Xml;
using WsdlGenerator.Xsd;

namespace WsdlGenerator.Configuration;

/// <summary>Turns command-line arguments into <see cref="GeneratorOptions"/>.</summary>
internal static class CommandLine
{
    public const string Usage =
        """
        Generates C# clients and services from WSDL.

        Usage:
          WsdlGenerator
              Regenerates this repository's Onvif bindings from the mirror in wsdl/.

          WsdlGenerator --wsdl <uri> --namespace <ns> --out <dir> [options]
              Generates from the given WSDLs.

        Options:
          --wsdl <uri>             A WSDL to generate from; repeat for more than one. Takes a file
                                   path or an http(s) URL. The service name comes from the file
                                   name, or write it as <name>=<uri> to choose one.
          --namespace <ns>         Root namespace. A service is generated into <ns>.<Service>.
          --out <dir>              Directory to write to. A service goes in <dir>/<Service>.
          --shared-namespace <ns>  Namespace for the types the services share. Defaults to
                                   <ns>.Schema.
          --shared-out <dir>       Directory for the shared types. Defaults to <dir>/Schema.
          --runtime-namespace <ns> Namespace of the runtime the generated code is compiled
                                   against: the client base class, the SOAP envelope, the XML
                                   reading and writing, and the interfaces the base class talks
                                   through. Defaults to <ns>.Runtime.
          --runtime-out <dir>      Directory to write that runtime to. Defaults to <dir>/Runtime.
                                   Pass --no-runtime instead to compile against a copy that
                                   already exists, which is what a second run generating into the
                                   same solution wants.
          --no-runtime             Do not write the runtime; --runtime-namespace names the one to
                                   use.
          --settings <type>        Type a generated client builds its settings from when it is
                                   given none, implementing the generated IClientSettings. Without
                                   it a client is only ever handed settings, having nothing it
                                   could construct.
          --dispatch <ns>          Namespace a generated service is routed by. Defaults to
                                   SharpOnvifServer.Dispatch, which is the only part of a
                                   generated service that is not generated.
          --client                 Generate clients only. Both sides are generated by default.
          --server                 Generate services only.
          --mirror <dir>           Resolve every document from this directory rather than from
                                   disk and the network, using the layout wsdl/fetch.sh writes.
          --enum-value <t>=<v>     Add a value to a schema enumeration that the schema does not
                                   list, for when a published schema trails what implementations
                                   actually send. The type is written {namespace}LocalName, so
                                   --enum-value "{http://example.com/s}Codec=AV1". Repeat for more.
          --help                   Show this.

        A generated client depends on nothing but the runtime written beside it, which is why that
        runtime is written rather than referenced. What is behind the runtime's interfaces is not
        generated: authenticating and logging are the calling library's business, and a client
        given neither still talks to a service that wants neither. A generated service also names
        the dispatch it is routed by - SharpOnvifServer's unless --dispatch says otherwise - which
        is a library rather than anything a schema describes.
        """;

    /// <summary>
    /// Parses arguments. Returns null when the run was not configured on the command line, which
    /// means the caller should fall back to regenerating this repository's own bindings.
    /// </summary>
    public static GeneratorOptions? Parse(IReadOnlyList<string> arguments)
    {
        var wsdls = new List<string>();
        string? rootNamespace = null;
        string? output = null;
        string? sharedNamespace = null;
        string? sharedOutput = null;
        string? runtimeNamespace = null;
        string? runtimeOutput = null;
        bool noRuntime = false;
        string? mirror = null;
        var enumValues = new List<EnumerationExtension>();
        string? settingsType = null;
        string? dispatchNamespace = null;
        bool client = false;
        bool server = false;

        for (int i = 0; i < arguments.Count; i++)
        {
            switch (arguments[i])
            {
                case "--wsdl": wsdls.Add(Value(arguments, ref i)); break;
                case "--namespace": rootNamespace = Value(arguments, ref i); break;
                case "--out": output = Value(arguments, ref i); break;
                case "--shared-namespace": sharedNamespace = Value(arguments, ref i); break;
                case "--shared-out": sharedOutput = Value(arguments, ref i); break;
                case "--runtime-namespace": runtimeNamespace = Value(arguments, ref i); break;
                case "--runtime-out": runtimeOutput = Value(arguments, ref i); break;
                case "--no-runtime": noRuntime = true; break;
                case "--settings": settingsType = Value(arguments, ref i); break;
                case "--dispatch": dispatchNamespace = Value(arguments, ref i); break;
                case "--mirror": mirror = Value(arguments, ref i); break;
                case "--enum-value": enumValues.Add(ToEnumerationExtension(Value(arguments, ref i))); break;
                case "--client": client = true; break;
                case "--server": server = true; break;
                default:
                    throw new SchemaException($"Unrecognised argument '{arguments[i]}'.");
            }
        }

        if (wsdls.Count == 0) return null;

        if (rootNamespace is null) throw new SchemaException("--namespace is required with --wsdl.");
        if (output is null) throw new SchemaException("--out is required with --wsdl.");

        // Neither flag means both sides, which is what a caller who says nothing wants.
        if (!client && !server) client = server = true;

        if (noRuntime && runtimeOutput is not null)
            throw new SchemaException("--no-runtime and --runtime-out ask for opposite things.");

        string root = Path.GetFullPath(output);

        return new GeneratorOptions
        {
            Services = wsdls.Select(ToService).ToList(),
            MirrorRoot = mirror is null ? null : Path.GetFullPath(mirror),
            SharedNamespace = sharedNamespace ?? rootNamespace + ".Schema",
            SharedDirectory = sharedOutput is null ? Path.Combine(root, "Schema") : Path.GetFullPath(sharedOutput),
            Targets = [new GenerationTarget(rootNamespace, root, client, server)],
            Runtime = new RuntimeTarget(
                runtimeNamespace ?? rootNamespace + ".Runtime",
                noRuntime ? null
                    : runtimeOutput is null ? Path.Combine(root, "Runtime") : Path.GetFullPath(runtimeOutput)),
            SettingsType = settingsType,
            DispatchNamespace = dispatchNamespace ?? "SharpOnvifServer.Dispatch",
            EnumerationExtensions = enumValues,
        };
    }

    /// <summary>
    /// Reads an <c>--enum-value</c> value: a type in <c>{namespace}LocalName</c> form - the same
    /// form <see cref="QName.ToString"/> writes - then '=', then the value to add.
    /// </summary>
    private static EnumerationExtension ToEnumerationExtension(string argument)
    {
        int separator = argument.IndexOf('=');
        if (separator <= 0 || separator == argument.Length - 1)
            throw new SchemaException($"--enum-value wants <type>=<value>, not '{argument}'.");

        string type = argument.Substring(0, separator).Trim();
        string value = argument.Substring(separator + 1).Trim();

        if (!type.StartsWith('{'))
            throw new SchemaException(
                $"--enum-value names the type as {{namespace}}LocalName, not '{type}'. A type in no namespace is written {{}}LocalName.");

        int close = type.IndexOf('}');
        if (close < 0)
            throw new SchemaException($"--enum-value type '{type}' has no closing brace.");

        string localName = type.Substring(close + 1);
        if (localName.Length == 0)
            throw new SchemaException($"--enum-value type '{type}' names a namespace but no type.");

        return new EnumerationExtension(new QName(type.Substring(1, close - 1), localName), value);
    }

    private static string Value(IReadOnlyList<string> arguments, ref int index)
    {
        if (index + 1 >= arguments.Count) throw new SchemaException($"'{arguments[index]}' needs a value.");
        return arguments[++index];
    }

    /// <summary>
    /// Reads a <c>--wsdl</c> value. The service name decides the namespace and folder a service is
    /// generated into, and is taken from the document's file name unless one is given.
    /// </summary>
    private static ServiceDefinition ToService(string argument)
    {
        int separator = argument.IndexOf('=');
        if (separator > 0)
            return new ServiceDefinition(argument.Substring(0, separator), argument.Substring(separator + 1));

        string name = Path.GetFileNameWithoutExtension(argument);
        if (name.Length == 0) throw new SchemaException($"Could not derive a service name from '{argument}'.");

        return new ServiceDefinition(Binding.CsharpNaming.Identifier(Capitalise(name)), argument);
    }

    private static string Capitalise(string value) =>
        value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value.Substring(1);
}
