using WsdlGenerator.Xml;

namespace WsdlGenerator.Configuration;

/// <summary>Turns command-line arguments into <see cref="GeneratorOptions"/>.</summary>
internal static class CommandLine
{
    public const string Usage =
        """
        Generates C# clients and services from WSDL.

        Usage:
          WsdlGenerator
              Regenerates this repository's Onvif bindings from the mirror in wsdl/.

          WsdlGenerator --wsdl <uri> --namespace <ns> --out <dir> [options]
              Generates from the given WSDLs.

        Options:
          --wsdl <uri>             A WSDL to generate from; repeat for more than one. Takes a file
                                   path or an http(s) URL. The service name comes from the file
                                   name, or write it as <name>=<uri> to choose one.
          --namespace <ns>         Root namespace. A service is generated into <ns>.<Service>.
          --out <dir>              Directory to write to. A service goes in <dir>/<Service>.
          --shared-namespace <ns>  Namespace for the types the services share. Defaults to
                                   <ns>.Schema.
          --shared-out <dir>       Directory for the shared types. Defaults to <dir>/Schema.
          --client                 Generate clients only. Both sides are generated by default.
          --server                 Generate services only.
          --mirror <dir>           Resolve every document from this directory rather than from
                                   disk and the network, using the layout wsdl/fetch.sh writes.
          --help                   Show this.

        Generated code depends on the SharpOnvifCommon runtime, and the server side additionally
        on SharpOnvifServer. Neither is specific to Onvif: they carry the SOAP 1.2 envelope, the
        XML reading and writing, and the ASP.NET Core dispatch that the generated code drives.
        """;

    /// <summary>
    /// Parses arguments. Returns null when the run was not configured on the command line, which
    /// means the caller should fall back to regenerating this repository's own bindings.
    /// </summary>
    public static GeneratorOptions? Parse(IReadOnlyList<string> arguments)
    {
        var wsdls = new List<string>();
        string? rootNamespace = null;
        string? output = null;
        string? sharedNamespace = null;
        string? sharedOutput = null;
        string? mirror = null;
        bool client = false;
        bool server = false;

        for (int i = 0; i < arguments.Count; i++)
        {
            switch (arguments[i])
            {
                case "--wsdl": wsdls.Add(Value(arguments, ref i)); break;
                case "--namespace": rootNamespace = Value(arguments, ref i); break;
                case "--out": output = Value(arguments, ref i); break;
                case "--shared-namespace": sharedNamespace = Value(arguments, ref i); break;
                case "--shared-out": sharedOutput = Value(arguments, ref i); break;
                case "--mirror": mirror = Value(arguments, ref i); break;
                case "--client": client = true; break;
                case "--server": server = true; break;
                default:
                    throw new SchemaException($"Unrecognised argument '{arguments[i]}'.");
            }
        }

        if (wsdls.Count == 0) return null;

        if (rootNamespace is null) throw new SchemaException("--namespace is required with --wsdl.");
        if (output is null) throw new SchemaException("--out is required with --wsdl.");

        // Neither flag means both sides, which is what a caller who says nothing wants.
        if (!client && !server) client = server = true;

        string root = Path.GetFullPath(output);

        return new GeneratorOptions
        {
            Services = wsdls.Select(ToService).ToList(),
            MirrorRoot = mirror is null ? null : Path.GetFullPath(mirror),
            SharedNamespace = sharedNamespace ?? rootNamespace + ".Schema",
            SharedDirectory = sharedOutput is null ? Path.Combine(root, "Schema") : Path.GetFullPath(sharedOutput),
            Targets = [new GenerationTarget(rootNamespace, root, client, server)],
        };
    }

    private static string Value(IReadOnlyList<string> arguments, ref int index)
    {
        if (index + 1 >= arguments.Count) throw new SchemaException($"'{arguments[index]}' needs a value.");
        return arguments[++index];
    }

    /// <summary>
    /// Reads a <c>--wsdl</c> value. The service name decides the namespace and folder a service is
    /// generated into, and is taken from the document's file name unless one is given.
    /// </summary>
    private static ServiceDefinition ToService(string argument)
    {
        int separator = argument.IndexOf('=');
        if (separator > 0)
            return new ServiceDefinition(argument.Substring(0, separator), argument.Substring(separator + 1));

        string name = Path.GetFileNameWithoutExtension(argument);
        if (name.Length == 0) throw new SchemaException($"Could not derive a service name from '{argument}'.");

        return new ServiceDefinition(Binding.CsharpNaming.Identifier(Capitalise(name)), argument);
    }

    private static string Capitalise(string value) =>
        value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value.Substring(1);
}
