<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net481;net8.0;net10.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) ">
		<Reference Include="System.Net.Http" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Runtime.Caching" Version="10.0.12" />
	</ItemGroup>

</Project>
