//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnvifScAccessRules
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", ConfigurationName="OnvifScAccessRules.AccessRulesPort")]
    public interface AccessRulesPort
    {
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/GetServiceCapabilities")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Capabilities")]
        OnvifScAccessRules.ServiceCapabilities GetServiceCapabilities();
        
        // CODEGEN: Parameter 'AccessProfileInfo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileInfo")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AccessProfileInfo")]
        OnvifScAccessRules.GetAccessProfileInfoResponse GetAccessProfileInfo(OnvifScAccessRules.GetAccessProfileInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileInfoList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessRules.GetAccessProfileInfoListResponse GetAccessProfileInfoList(OnvifScAccessRules.GetAccessProfileInfoListRequest request);
        
        // CODEGEN: Parameter 'AccessProfile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfiles")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="AccessProfile")]
        OnvifScAccessRules.GetAccessProfilesResponse GetAccessProfiles(OnvifScAccessRules.GetAccessProfilesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileList")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        OnvifScAccessRules.GetAccessProfileListResponse GetAccessProfileList(OnvifScAccessRules.GetAccessProfileListRequest request);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/CreateAccessProfile")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: CoreWCF.MessageParameterAttribute(Name="Token")]
        string CreateAccessProfile(OnvifScAccessRules.AccessProfile AccessProfile);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/ModifyAccessProfile")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void ModifyAccessProfile(OnvifScAccessRules.AccessProfile AccessProfile);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/SetAccessProfile")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void SetAccessProfile(OnvifScAccessRules.AccessProfile AccessProfile);
        
        [CoreWCF.OperationContractAttribute(Action="http://www.onvif.org/ver10/accessrules/wsdl/DeleteAccessProfile")]
        [CoreWCF.XmlSerializerFormatAttribute()]
        [CoreWCF.ServiceKnownTypeAttribute(typeof(DataEntity))]
        void DeleteAccessProfile(string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class ServiceCapabilities
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private uint maxLimitField;
        
        private uint maxAccessProfilesField;
        
        private uint maxAccessPoliciesPerAccessProfileField;
        
        private bool multipleSchedulesPerAccessPointSupportedField;
        
        private bool clientSuppliedTokenSupportedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public ServiceCapabilities()
        {
            this.clientSuppliedTokenSupportedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAccessProfiles
        {
            get
            {
                return this.maxAccessProfilesField;
            }
            set
            {
                this.maxAccessProfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAccessPoliciesPerAccessProfile
        {
            get
            {
                return this.maxAccessPoliciesPerAccessProfileField;
            }
            set
            {
                this.maxAccessPoliciesPerAccessProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MultipleSchedulesPerAccessPointSupported
        {
            get
            {
                return this.multipleSchedulesPerAccessPointSupportedField;
            }
            set
            {
                this.multipleSchedulesPerAccessPointSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class AccessProfileExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class AccessPolicyExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class AccessPolicy
    {
        
        private string scheduleTokenField;
        
        private string entityField;
        
        private System.Xml.XmlQualifiedName entityTypeField;
        
        private AccessPolicyExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ScheduleToken
        {
            get
            {
                return this.scheduleTokenField;
            }
            set
            {
                this.scheduleTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlQualifiedName EntityType
        {
            get
            {
                return this.entityTypeField;
            }
            set
            {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AccessPolicyExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessProfileInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class AccessProfileInfo : DataEntity
    {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl")]
    public partial class AccessProfile : AccessProfileInfo
    {
        
        private AccessPolicy[] accessPolicyField;
        
        private AccessProfileExtension extensionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccessPolicy", Order=0)]
        public AccessPolicy[] AccessPolicy
        {
            get
            {
                return this.accessPolicyField;
            }
            set
            {
                this.accessPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccessProfileExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileInfo", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileInfoRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAccessProfileInfoRequest()
        {
        }
        
        public GetAccessProfileInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileInfoResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfileInfo")]
        public OnvifScAccessRules.AccessProfileInfo[] AccessProfileInfo;
        
        public GetAccessProfileInfoResponse()
        {
        }
        
        public GetAccessProfileInfoResponse(OnvifScAccessRules.AccessProfileInfo[] AccessProfileInfo)
        {
            this.AccessProfileInfo = AccessProfileInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileInfoList", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileInfoListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=1)]
        public string StartReference;
        
        public GetAccessProfileInfoListRequest()
        {
        }
        
        public GetAccessProfileInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileInfoListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfileInfo")]
        public OnvifScAccessRules.AccessProfileInfo[] AccessProfileInfo;
        
        public GetAccessProfileInfoListResponse()
        {
        }
        
        public GetAccessProfileInfoListResponse(string NextStartReference, OnvifScAccessRules.AccessProfileInfo[] AccessProfileInfo)
        {
            this.NextStartReference = NextStartReference;
            this.AccessProfileInfo = AccessProfileInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfiles", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfilesRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAccessProfilesRequest()
        {
        }
        
        public GetAccessProfilesRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfilesResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfile")]
        public OnvifScAccessRules.AccessProfile[] AccessProfile;
        
        public GetAccessProfilesResponse()
        {
        }
        
        public GetAccessProfilesResponse(OnvifScAccessRules.AccessProfile[] AccessProfile)
        {
            this.AccessProfile = AccessProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileList", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileListRequest
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        public int Limit;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=1)]
        public string StartReference;
        
        public GetAccessProfileListRequest()
        {
        }
        
        public GetAccessProfileListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CoreWCF", "4.0.0.0")]
    [CoreWCF.MessageContractAttribute(WrapperName="GetAccessProfileListResponse", WrapperNamespace="http://www.onvif.org/ver10/accessrules/wsdl", IsWrapped=true)]
    public partial class GetAccessProfileListResponse
    {
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=0)]
        public string NextStartReference;
        
        [CoreWCF.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/accessrules/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AccessProfile")]
        public OnvifScAccessRules.AccessProfile[] AccessProfile;
        
        public GetAccessProfileListResponse()
        {
        }
        
        public GetAccessProfileListResponse(string NextStartReference, OnvifScAccessRules.AccessProfile[] AccessProfile)
        {
            this.NextStartReference = NextStartReference;
            this.AccessProfile = AccessProfile;
        }
    }
}
